/*jslint nomen: true, plusplus: false, sloppy: true, white:true*/
/*jshint nomen: false, curly: true, plusplus: false, expr:true, undef:true, newcap:true, latedef:true, camelcase:true  */
/*global module: false, iScroll:false, setTimeout: false, document:false, WebKitCSSMatrix:false, _: false, Backbone: false, backbone: false, $: false, define: false, require: false, console: false, window:false */

var test 		= require('tap').test,
	_ 			= require('underscore'),
	development = require('./../lib/development');

test('environments are set correctly', function(t) {

	t.ok(_.isArray(development(new Error("message"))), 'dev logger returns data array \
		(ie log message generated by logData Class)');

	t.end();
});
