/*jslint nomen: true, plusplus: false, sloppy: true, white:true*/
/*jshint nomen: false, curly: true, plusplus: false, expr:true, undef:true, newcap:true, latedef:true, camelcase:true  */
/*global module: false, iScroll:false, setTimeout: false, document:false, WebKitCSSMatrix:false, _: false, Backbone: false, backbone: false, $: false, define: false, require: false, console: false, window:false */

var _          = require('underscore'),
	printError = require('./print-error');

// if in dev then deeply inspect every error
var devLogging = function (err, req) {
	// return data (ie log message generated by logData Class)
	// data shd be an array
	var	printErr = (_.isFunction(this.printError) && this.printError) || printError;
	return printErr(err, req);
};

module.exports = devLogging;